function output = process_run(id, input, log)
    log.info(log.l, 'Decoding input image');
    if(exist('./code/','dir'))
		addpath('./code/');
	end
     
    imbytes = input.image.data;
     
    tn = tempname;
    fileID = fopen(tn,'w');
    fwrite(fileID,imbytes);
    fclose(fileID);
     
%     img = imread(tn);
%     figure();
%     imshow(img); 
     
    [score] = MOD3(tn); 
    
    if(score==-1)
        no_prediction = 'true';
    else
        no_prediction = 'false';
    end
	
	if(score>0.5)
		is_manipulated = 'true';
	else
		is_manipulated = 'false';
	end
 
    log.info(log.l, 'Done');
    output = struct( 'algorithm', struct( ...
										'name', 'unifi_mod3',...
										'version','1.0', ...
										'description','face splicing detection by light analysis', ...
										'manipulations_detected', 'splice', ...
										'algotithm_type','physical', ...
										'media_type','image')  , ...
				'no_prediction',no_prediction, ...
				'is_manipulated',is_manipulated, ...
				'detections',struct( ...
										'confidence', num2str(score), ...
										'specificity','global', ...
										'manip_name','splice', ...
										'manip_description','face splicing detection by light analysis', ...
										'manip_explanation','for each face the illuminat environment coefficients are estimated and compared. Differences indicate a tampering.') ...
			);
end
